# bzfm zsh integration
# Generated by 'bzfm init zsh'

# Insert selected bookmarks into current command line (Ctrl+O)
function __bzfm_insert_bookmark() {
  local selection
  selection=$(bzfm select --multi)
  if [[ -z "$selection" ]]; then
    zle reset-prompt
    return 0
  fi
  LBUFFER+="${selection//$'\n'/ }"
  zle reset-prompt
}

zle -N __bzfm_insert_bookmark
if [[ -z $BZFM_NO_BINDINGS ]]; then
  bindkey '^O' __bzfm_insert_bookmark
fi

# cd into selected bookmark directory (Ctrl+P)
function __bzfm_cd_to_bookmark() {
  local dir
  dir=$(bzfm select --dirs)
  if [[ -z "$dir" ]]; then
    zle redisplay
    return 0
  fi
  BUFFER="cd $dir"
  zle accept-line
}

zle -N __bzfm_cd_to_bookmark
if [[ -z $BZFM_NO_BINDINGS ]]; then
  bindkey '^P' __bzfm_cd_to_bookmark
fi

# f: jump to directory via bzfm
function f() {
  local dir
  if [[ -z "$*" ]]; then
    dir=$(bzfm select --dirs)
  else
    dir=$(bzfm query --dirs "$@")
  fi
  if [[ -z "$dir" ]]; then
    return 0
  fi
  cd "$dir"
}

# {ALIAS_BLOCK}
