# bzfm fish integration
# Generated by 'bzfm init fish'

function __bzfm_insert_bookmark --description 'Insert bzfm bookmark(s) into current command line'
  set -l selection (bzfm select --multi)
  if test -z "$selection"
    commandline -f repaint
    return 0
  end
  set -l current (commandline)
  set current "$current $selection"
  commandline --replace -- "$current"
  commandline -f repaint
end

function __bzfm_cd_to_bookmark --description 'cd to bzfm bookmarked directory'
  set -l dir (bzfm select --dirs)
  if test -z "$dir"
    commandline -f repaint
    return 0
  end
  commandline --replace -- "cd $dir"
  commandline -f execute
end

if test -z "$BZFM_NO_BINDINGS"
  bind \co '__bzfm_insert_bookmark'
  bind \cp '__bzfm_cd_to_bookmark'
end

# {ALIAS_BLOCK}
